language: generic
sudo: required
services:
  - docker
 
before_install:
  - docker build -t krabidzus/docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true krabidzus/docker-react npm run test -- --coverage